### ISSUE TITLE
Changing display name to one already in use by another user throws an internal server error

### ISSUE THREAD

**Issue by LogalDeveloper** [RedstonerServer/redstoner.com#35]
If you attempt to change your display name to something that another user is using or has the IGN of, it throws an error 500.

Let's say for example I am user `LogalDeveloper` and want to change my display name to `Logal`, but another user already has that as their IGN. What was expected to happen was the website show an error banner saying that the name is already in use, but what actually happens is the web server returns an error 500.

**Comment by bruncbrunc** [comment]
Solved in commit `5f17385`.
