### ISSUE TITLE
RawGit is shutting down

### ISSUE THREAD

**Issue by jomo** [RedstonerServer/redstoner.com#52]
[Announcement](https://rawgit.com/):
> GitHub repositories that served content through RawGit within the last month will continue to be served until at least October of 2019. URLs for other repositories are no longer being served.
> 
> If you're currently using RawGit, please stop using it as soon as you can.

It's currently used for [jomo/ago.js](https://github.com/jomo/ago.js) here:

https://github.com/RedstonerServer/redstoner.com/blob/9b3ae8b399e1e152cf4a6dfd2357120f04213b60/app/views/layouts/application.html.erb#L13

**Comment by jomo** [comment]
Replacing the URL with `https://cdn.jsdelivr.net/gh/jomo/ago.js@0.0.1/ago.min.js` should do.

**Comment by LogalDeveloper** [comment]
Thanks for the warning! I’ll get this updated as soon as I can.

**Comment by LogalDeveloper** [comment]
The change of the CDN, along with a few other changes that have been waiting for a while, has been deployed to the production server.
